language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t gabrielmojica/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gabrielmojica/docker-react npm run test